### ISSUE TITLE
Error in subject uri due to @base uri

### ISSUE THREAD

**Issue by RichDijk** [SDM-TIB/SDM-RDFizer#76] opened 2022-02-08 19:18 UTC
**Describe the bug**

With 
`@base <http://base.org#>
`
and
```
    rr:subjectMap [
    	a rr:Subject;
    	rr:termType rr:IRI;
    	rr:template "http://www.data.nl#mem_{Client_ID}_{Categorie}";
    	rr:class vph-g:FreedomRestrictionEvent;
    ];
```

`<http://base.org#>.http://www.data.nl#mem_410314_20031> ...
`

**Expected behavior**
With RMLmapper:
` <http://www.data.nl#mem_410314_20031> ....
`

** Used: **
Windows 10  with latest release rdfizer, rdflib 6.1 and 4.2 give the same result

**Comment by eiglesias34** [comment] 2022-02-09 14:13
Hello @RichDijk,

First of all, thank you for using the SDM-RDFizer. I found the problem and fixed it. Please test it out. Please take into consideration, that I updated the code but not the library. After I get the confirmation that the problem is fixed I will update the library and close this issue.

Thank you again,
Enrique Iglesias.

**Comment by RichDijk** [comment] 2022-02-09 17:50
Hi Enrique,

Thank you for solving the issue.

I tried to install the latest commit with
python -m pip install git+https://github.com/SDM-TIB/SDM-RDFizer.git@916f1412f65260c15f1c884003c35593df2ac2d8

but got an error
ERROR: git+https://github.com/SDM-TIB/SDM-RDFizer.git@916f1412f65260c15f1c884003c35593df2ac2d8 does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.

I must be doing something wrong :(

**Comment by RichDijk** [comment] 2022-02-09 18:14
I was thinking too difficult. Your patch works fine, thank you.

**Comment by eiglesias34** [comment] 2022-02-09 18:15
That is great. I will close the issue now. Thank you again for using the SDM-RDFizer.

**Closed by eiglesias34** 2022-02-09 18:15 UTC
