### ISSUE TITLE
A blank node created using rdfizer (4.0.1.3) on Windows 10 is a literal

### ISSUE THREAD

**Issue by RichDijk** [SDM-TIB/SDM-RDFizer#74] opened 2022-01-04 15:20 UTC
A blank node created using rdfizer (4.0.1.3) on Windows 10 is a literal.

I have used the following mapping

```
    rr:predicateObjectMap [
        rr:predicate vph-g:hasQuality ;
        rr:objectMap [
            rr:template "ernst_{wond_id}_{categorie}" ;
            rr:termType rr:BlankNode
        ]
    ];
```
Which results in:

`<http://decubituswond_1-1> <http://purl.org/ozo/vph-g#hasQuality> "ernst_1-1_2".`

RMLmapper produces that what I expect

`<http://decubituswond_1-1> <http://purl.org/ozo/vph-g#hasQuality> _:ernst_1-1_2.`

I use rdflib 4.2.2. but have the same behaviour using rdflib 6.1.1.

**Comment by eiglesias34** [comment] 2022-01-10 12:09
Hello @RichDijk,  

First of all, thank you for using the SDM-RDFizer. I found the problem and fixed it. Please test it out. Please take into consideration, that I updated the code but not the library. After I get the confirmation that the problem is fixed I will update the library and close this issue.

Thank you again,
Enrique Iglesias.

**Comment by eiglesias34** [comment] 2022-01-17 10:31
Thank you again for your interest in the SDM-RDFizer. I going to close this issue now. All the changes have been updated in the library.

**Closed by eiglesias34** 2022-01-17 10:31 UTC
Labels: bug
